// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rujuk-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Room struct {
	// id ruangan
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// nama ruangan
	Nama string `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	// tipe ruangan
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// jumlah
	Jumlah               int32    `protobuf:"varint,4,opt,name=jumlah,proto3" json:"jumlah,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d65929248c863de, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *Room) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Room) GetJumlah() int32 {
	if m != nil {
		return m.Jumlah
	}
	return 0
}

type Pasien struct {
	// nama pasien
	Nama string `protobuf:"bytes,1,opt,name=nama,proto3" json:"nama,omitempty"`
	// diagnosa penyakit
	Diagnosa             string   `protobuf:"bytes,2,opt,name=diagnosa,proto3" json:"diagnosa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pasien) Reset()         { *m = Pasien{} }
func (m *Pasien) String() string { return proto.CompactTextString(m) }
func (*Pasien) ProtoMessage()    {}
func (*Pasien) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d65929248c863de, []int{1}
}

func (m *Pasien) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pasien.Unmarshal(m, b)
}
func (m *Pasien) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pasien.Marshal(b, m, deterministic)
}
func (m *Pasien) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pasien.Merge(m, src)
}
func (m *Pasien) XXX_Size() int {
	return xxx_messageInfo_Pasien.Size(m)
}
func (m *Pasien) XXX_DiscardUnknown() {
	xxx_messageInfo_Pasien.DiscardUnknown(m)
}

var xxx_messageInfo_Pasien proto.InternalMessageInfo

func (m *Pasien) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *Pasien) GetDiagnosa() string {
	if m != nil {
		return m.Diagnosa
	}
	return ""
}

type RequestRujuk struct {
	// id ruangan
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pasien               *Pasien  `protobuf:"bytes,2,opt,name=pasien,proto3" json:"pasien,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestRujuk) Reset()         { *m = RequestRujuk{} }
func (m *RequestRujuk) String() string { return proto.CompactTextString(m) }
func (*RequestRujuk) ProtoMessage()    {}
func (*RequestRujuk) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d65929248c863de, []int{2}
}

func (m *RequestRujuk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRujuk.Unmarshal(m, b)
}
func (m *RequestRujuk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRujuk.Marshal(b, m, deterministic)
}
func (m *RequestRujuk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRujuk.Merge(m, src)
}
func (m *RequestRujuk) XXX_Size() int {
	return xxx_messageInfo_RequestRujuk.Size(m)
}
func (m *RequestRujuk) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRujuk.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRujuk proto.InternalMessageInfo

func (m *RequestRujuk) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestRujuk) GetPasien() *Pasien {
	if m != nil {
		return m.Pasien
	}
	return nil
}

type Response struct {
	// response code
	Kode int32 `protobuf:"varint,1,opt,name=kode,proto3" json:"kode,omitempty"`
	// message response
	Pesan                string   `protobuf:"bytes,2,opt,name=pesan,proto3" json:"pesan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d65929248c863de, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetKode() int32 {
	if m != nil {
		return m.Kode
	}
	return 0
}

func (m *Response) GetPesan() string {
	if m != nil {
		return m.Pesan
	}
	return ""
}

type FetchRequest struct {
	// cursor
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d65929248c863de, []int{4}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Room)(nil), "v1.Room")
	proto.RegisterType((*Pasien)(nil), "v1.Pasien")
	proto.RegisterType((*RequestRujuk)(nil), "v1.RequestRujuk")
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*FetchRequest)(nil), "v1.FetchRequest")
}

func init() { proto.RegisterFile("rujuk-service.proto", fileDescriptor_3d65929248c863de) }

var fileDescriptor_3d65929248c863de = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xbd, 0x4f, 0xfb, 0x30,
	0x10, 0xad, 0xf3, 0x6b, 0xa2, 0xfe, 0xae, 0x01, 0x21, 0x83, 0x50, 0xd4, 0xa9, 0xf2, 0xd4, 0x01,
	0x0a, 0x2d, 0x0c, 0x0c, 0x2c, 0x30, 0xc0, 0x8a, 0x8c, 0xc4, 0x6e, 0x9a, 0x2b, 0x75, 0x9b, 0xc4,
	0x21, 0x76, 0x22, 0xf1, 0xdf, 0x23, 0x7f, 0x34, 0x8a, 0xc4, 0x76, 0xef, 0x39, 0xef, 0xe3, 0x2e,
	0x70, 0xde, 0xb4, 0xfb, 0xf6, 0x70, 0xad, 0xb1, 0xe9, 0xe4, 0x06, 0x97, 0x75, 0xa3, 0x8c, 0xa2,
	0x51, 0xb7, 0x62, 0x1f, 0x30, 0xe6, 0x4a, 0x95, 0xf4, 0x14, 0x22, 0x99, 0x67, 0x64, 0x4e, 0x16,
	0x27, 0x3c, 0x92, 0x39, 0xa5, 0x30, 0xae, 0x44, 0x29, 0xb2, 0x68, 0x4e, 0x16, 0xff, 0xb9, 0x9b,
	0x2d, 0x67, 0x7e, 0x6a, 0xcc, 0xfe, 0x79, 0xce, 0xce, 0xf4, 0x12, 0x92, 0x7d, 0x5b, 0x16, 0x62,
	0x97, 0x8d, 0xe7, 0x64, 0x11, 0xf3, 0x80, 0xd8, 0x03, 0x24, 0x6f, 0x42, 0x4b, 0xac, 0x7a, 0x27,
	0x32, 0x70, 0x9a, 0xc1, 0x24, 0x97, 0xe2, 0xab, 0x52, 0xfa, 0x98, 0xd0, 0x63, 0xf6, 0x0c, 0x29,
	0xc7, 0xef, 0x16, 0xb5, 0xe1, 0xb6, 0xf3, 0x9f, 0x66, 0x0c, 0x92, 0xda, 0x39, 0x3b, 0xe5, 0x74,
	0x0d, 0xcb, 0x6e, 0xb5, 0xf4, 0x59, 0x3c, 0xbc, 0xb0, 0x7b, 0x98, 0x70, 0xd4, 0xb5, 0xaa, 0x34,
	0xda, 0xfc, 0x83, 0xca, 0xd1, 0x39, 0xc4, 0xdc, 0xcd, 0xf4, 0x02, 0xe2, 0x1a, 0xb5, 0xa8, 0x42,
	0xb8, 0x07, 0xec, 0x11, 0xd2, 0x17, 0x34, 0x9b, 0x5d, 0x88, 0xb7, 0xbb, 0xa9, 0xed, 0x56, 0xa3,
	0x09, 0xda, 0x80, 0xac, 0xba, 0x90, 0xa5, 0x34, 0x4e, 0x1d, 0x73, 0x0f, 0xd6, 0x25, 0xa4, 0xae,
	0xf0, 0xbb, 0xbf, 0x31, 0xbd, 0x02, 0x78, 0x45, 0xf3, 0x54, 0x14, 0xee, 0xbe, 0x67, 0xb6, 0xe5,
	0xd0, 0x7d, 0x36, 0xb1, 0x8c, 0x7d, 0x63, 0xa3, 0x5b, 0x42, 0x6f, 0x60, 0x7a, 0xdc, 0xba, 0xff,
	0x7c, 0x78, 0x86, 0x59, 0xea, 0x19, 0xbf, 0x14, 0x1b, 0x7d, 0x26, 0xee, 0x1f, 0xde, 0xfd, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xff, 0x8e, 0x87, 0x42, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RujukServiceClient is the client API for RujukService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RujukServiceClient interface {
	GetAllRoom(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (RujukService_GetAllRoomClient, error)
	RequestRoom(ctx context.Context, in *RequestRujuk, opts ...grpc.CallOption) (*Response, error)
}

type rujukServiceClient struct {
	cc *grpc.ClientConn
}

func NewRujukServiceClient(cc *grpc.ClientConn) RujukServiceClient {
	return &rujukServiceClient{cc}
}

func (c *rujukServiceClient) GetAllRoom(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (RujukService_GetAllRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RujukService_serviceDesc.Streams[0], "/v1.RujukService/GetAllRoom", opts...)
	if err != nil {
		return nil, err
	}
	x := &rujukServiceGetAllRoomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RujukService_GetAllRoomClient interface {
	Recv() (*Room, error)
	grpc.ClientStream
}

type rujukServiceGetAllRoomClient struct {
	grpc.ClientStream
}

func (x *rujukServiceGetAllRoomClient) Recv() (*Room, error) {
	m := new(Room)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rujukServiceClient) RequestRoom(ctx context.Context, in *RequestRujuk, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.RujukService/RequestRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RujukServiceServer is the server API for RujukService service.
type RujukServiceServer interface {
	GetAllRoom(*FetchRequest, RujukService_GetAllRoomServer) error
	RequestRoom(context.Context, *RequestRujuk) (*Response, error)
}

// UnimplementedRujukServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRujukServiceServer struct {
}

func (*UnimplementedRujukServiceServer) GetAllRoom(req *FetchRequest, srv RujukService_GetAllRoomServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllRoom not implemented")
}
func (*UnimplementedRujukServiceServer) RequestRoom(ctx context.Context, req *RequestRujuk) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRoom not implemented")
}

func RegisterRujukServiceServer(s *grpc.Server, srv RujukServiceServer) {
	s.RegisterService(&_RujukService_serviceDesc, srv)
}

func _RujukService_GetAllRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RujukServiceServer).GetAllRoom(m, &rujukServiceGetAllRoomServer{stream})
}

type RujukService_GetAllRoomServer interface {
	Send(*Room) error
	grpc.ServerStream
}

type rujukServiceGetAllRoomServer struct {
	grpc.ServerStream
}

func (x *rujukServiceGetAllRoomServer) Send(m *Room) error {
	return x.ServerStream.SendMsg(m)
}

func _RujukService_RequestRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRujuk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RujukServiceServer).RequestRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RujukService/RequestRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RujukServiceServer).RequestRoom(ctx, req.(*RequestRujuk))
	}
	return interceptor(ctx, in, info, handler)
}

var _RujukService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RujukService",
	HandlerType: (*RujukServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRoom",
			Handler:    _RujukService_RequestRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllRoom",
			Handler:       _RujukService_GetAllRoom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rujuk-service.proto",
}
